#!/bin/bash

# Add a small delay to ensure the USB device is fully initialized
sleep 2

for i in {1..4}; do
    if ! mountpoint -q /media/usb$i; then
        /usr/bin/pmount --umask 000 --noatime -w --sync $1 usb$i
        exit 0
    fi
done

echo "No mountpoints available!"
exit 1
